name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker images
        run: |
          # Build both frontend and backend Docker images using Docker Compose
          docker compose -f docker/production.docker-compose.yml build

      - name: Deploy containers
        run: |
          # Stop and remove existing containers to free up ports and names
          docker compose -f docker/production.docker-compose.yml down
          
          # Start new containers in detached mode with build
          docker compose -f docker/production.docker-compose.yml up -d --build
          
          # Prune unused images to free up space
          docker image prune -af