name: CI Pipeline

on:
  push:
    branches:
      - main  # Change to your default branch if it's different

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root -p${{ secrets.DB_ROOT_PASSWORD }}"
          --health-interval=30s
          --health-timeout=10s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Frontend Docker Image
        run: |
          docker build -f docker/pet-adoption-frontend.Dockerfile -t yourusername/pet-adoption-frontend:latest .

      - name: Build Backend Docker Image
        run: |
          docker build -f docker/pet-adoption-api.Dockerfile -t yourusername/pet-adoption-api:latest .

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Push Frontend Docker Image
        run: |
          docker push yourusername/pet-adoption-frontend:latest

      - name: Push Backend Docker Image
        run: |
          docker push yourusername/pet-adoption-api:latest

      - name: Deploy to Production Server
        run: |
          ssh -o StrictHostKeyChecking=no user@your-production-server-ip "docker pull yourusername/pet-adoption-frontend:latest && docker pull yourusername/pet-adoption-api:latest && docker-compose -f /path/to/your/docker-compose.yml up -d"
